### ISSUE TITLE
Control stratisd's initial configuration with a configuration

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#358]
Currently, stratisd's behavior on start up is to search for block devices that contain Stratis metadata and then to assemble pools or sets of devices as appropriate.

Additional changes to stratisd's initial configuration can be accomplished by running scripts which interact with stratisd's IPC layers either directly or via the two existing Stratis CLIs.

It could also be possible to start stratisd and assemble pools according to a specified, declarative configuration. Such a configuration would be expected to bypass the IPC layers and communicate directly with the stratisd engine.

Such a configuration file could get as hopelessly intricate as it wanted. Everybody loves toml format, and so does Rust, so we would expect to use that.

An example of a configuration file, adapted from a CoreOs example configuration[1]:

```
pools:
  - name: <poolname>
    devices: [<devnode1>, <devnode2>]
    encryption:
       clevis:
          tang: <tang configuration here>
    filesystems:
      <filesystem1>:
        name: fs1
        size: 32 GiB
      <filesystem2>:
        name: fs2
```

It is important to note that Stratis makes regular use of UUIDs for identifying its filesystems, etc. This kind of general configuration file would not preserve these UUIDs across instances.

[1] https://coreos.github.io/butane/examples/#luks-encrypted-storage
